({	
	createTaskSummary: "A feladatot ${0} felhasználó hozta létre.",
	completeTaskSummary: "A feladatot ${0} felhasználó késznek jelölte.",
	editTaskSummary5: "${0} felhasználó módosította a feladat ${1}, ${2}, ${3}, ${4} és ${5} részét.",
	editTaskSummary4: "${0} felhasználó módosította a feladat ${1}, ${2}, ${3} és ${4} részét.",
	editTaskSummary3: "${0} felhasználó módosította a feladat ${1}, ${2} és ${3} részét.",
	editTaskSummary2: "${0} felhasználó módosította a feladat ${1} és ${2} részét.",
	editTaskSummary1: "${0} felhasználó módosította a feladat ${1} részét.",
	editTaskSummary0: "${0} felhasználó módosította a feladatot.",
	removeTaskSummary: "${0} felhasználó eltávolította a feladatot.",
	reopenTaskSummary: "${0} felhasználó újra megnyitotta a feladatot.",
	reassignTaskSummary: "${0} felhasználó átruházta a(z) ${1} feladatot ${2} felhasználóról ${3} felhasználóra.",
	reassignTaskSummary2: "${0} felhasználó ${1} megbízottról ${2} megbízottra, valamint ${3} ellenőrről ${4} ellenőrre ruházta át a feladatot.",
	workPrivateSummary: "${0} felhasználó önállóan kezdett dolgozni ezen a feladaton.",
	approveTaskSummary: "${0} felhasználó jóváhagyta ezt a feladatot.",
	rejectTaskSummary: "${0} felhasználó visszautasította ezt a feladatot.",
	rejectTaskSummary2: "${0} felhasználó visszaadta ezt a feladatot ${1} felhasználónak átdolgozásra.",
	submitTaskSummary: "${0} felhasználó visszaküldte az önálló munkát a dokumentumba.",
	cancelPrivateSummary: "${0} felhasználó visszavonta az önálló munkát.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "megbízott",
	fieldDuedate: "esedékesség",
	fieldDescription: "leírás",
	fieldReviewer: "ellenőr",
	fieldTitle: "beosztás",
	emptyFieldValue: "[Nincs kiosztva]",
	errorAddMember:"Nem lehet hozzáférni a tevékenységkiszolgálóhoz megbízottak és ellenőrök hozzáadása céljából. Próbálja meg újra kicsit később.",
	errorCreateActivity:"Nem lehet hozzáférni a tevékenységkiszolgálóhoz a tevékenység létrehozása céljából. Próbálja meg újra kicsit később.",
	errorLoadActivity:"Nem lehet hozzáférni a tevékenységkiszolgálóhoz megbízások betöltése céljából. Próbálja meg újra kicsit később.",
	errorCreateAssignment: "Nem lehet hozzáférni a tevékenységkiszolgálóhoz a megbízás létrehozása céljából. Próbálja meg újra kicsit később.",
	errorDeleteAssignment: "Nem lehet hozzáférni a tevékenységkiszolgálóhoz megbízások törlése céljából. Próbálja meg újra kicsit később.",
	errorupdateAssignment: "Nem lehet hozzáférni a tevékenységkiszolgálóhoz megbízások frissítése céljából. Próbálja meg újra kicsit később.",
	errorSubmitAssignment: "Ön nem hajthatja végre ezt a műveletet. Ellenőrizze, hogy van-e hozzá jogosultsága.",	
	errorAddMember2:"Nem lehet hozzáférni a kiszolgálóhoz megbízottak és ellenőrök hozzáadása céljából. Próbálja meg újra kicsit később.",
	errorCreateActivity2:"Nem lehet hozzáférni a kiszolgálóhoz a tevékenység létrehozása céljából. Próbálja meg újra kicsit később.",
	errorLoadActivity2:"Nem lehet hozzáférni a kiszolgálóhoz megbízások betöltése céljából. Próbálja meg újra kicsit később.",
	errorCreateAssignment2: "Nem lehet hozzáférni a kiszolgálóhoz a megbízás létrehozása céljából. Próbálja meg újra kicsit később.",
	errorDeleteAssignment2: "Nem lehet hozzáférni a kiszolgálóhoz megbízások törlése céljából. Próbálja meg újra kicsit később.",
	errorupdateAssignment2: "Nem lehet hozzáférni a kiszolgálóhoz megbízások frissítése céljából. Próbálja meg újra kicsit később."	
})
